// Package full Code generated by swaggo/swag. DO NOT EDIT
package full

import "github.com/swaggo/swag"

const docTemplateinternal = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "tags": [
        {
            "description": "Liveness, readiness, and database migration version",
            "name": "health"
        },
        {
            "description": "Queue flight schedule and reference data import jobs",
            "name": "ingest"
        },
        {
            "description": "Inspect background job status",
            "name": "jobs"
        },
        {
            "description": "Route performance stats and booking outlook",
            "name": "routes"
        }
    ]
}`

// SwaggerInfointernal holds exported Swagger Info so clients can modify it
var SwaggerInfointernal = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "flight-tracker API",
	Description:      "REST API for flight data ingest, job status, and route performance.",
	InfoInstanceName: "internal",
	SwaggerTemplate:  docTemplateinternal,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfointernal.InstanceName(), SwaggerInfointernal)
}
