// Package full Code generated by swaggo/swag. DO NOT EDIT
package full

import "github.com/swaggo/swag"

const docTemplateinternal = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/db/version": {
            "get": {
                "description": "Returns the current schema migration version and dirty flag.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health",
                    "internal"
                ],
                "summary": "Database migration version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.MigrationVersion"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns ok when the HTTP server is up. Does not check the database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health",
                    "internal"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.StatusResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns ready when the database is reachable; otherwise returns 503.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health",
                    "internal"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.StatusResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handlers.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "store.MigrationVersion": {
            "type": "object",
            "properties": {
                "dirty": {
                    "type": "boolean"
                },
                "version": {
                    "type": "integer"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Liveness, readiness, and database migration version",
            "name": "health"
        },
        {
            "description": "Queue flight schedule and reference data import jobs",
            "name": "ingest"
        },
        {
            "description": "Inspect background job status",
            "name": "jobs"
        },
        {
            "description": "Route performance stats and booking outlook",
            "name": "routes"
        }
    ]
}`

// SwaggerInfointernal holds exported Swagger Info so clients can modify it
var SwaggerInfointernal = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "flight-tracker API",
	Description:      "REST API for flight data ingest, job status, and route performance.",
	InfoInstanceName: "internal",
	SwaggerTemplate:  docTemplateinternal,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfointernal.InstanceName(), SwaggerInfointernal)
}
