basePath: /
host: localhost:8080
info:
  contact: {}
  description: REST API for flight data ingest, job status, and route performance.
  title: flight-tracker API
  version: "1.0"
paths: {}
swagger: "2.0"
